{{- if .Values.wordpress.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
spec:
  accessModes:
    - {{ .Values.wordpress.persistence.accessMode }}
  storageClassName: {{ .Values.wordpress.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
{{- end }}

{{- if .Values.mysql.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  storageClassName: {{ .Values.mysql.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
{{- end }}

{{- if .Values.redis.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
